### ISSUE TITLE
css option is ignored for system and amd output

### ISSUE THREAD

**Issue by shirotech** [sveltejs/vite-plugin-svelte#207]
### Describe the bug

It seems when outputting to systemjs or amd, the css option is ignored and css files are not written to disk, instead they are still being injected in the js.

### Reproduction

Here is a sample config

```js
import {svelte} from '@sveltejs/vite-plugin-svelte';
import {defineConfig} from 'vite';

export default defineConfig({
  build: {
    rollupOptions: {
      output: [
        {
          dir: 'amd',
          format: 'amd',
        },
        {
          dir: 'system',
          format: 'system',
        },
        {
          dir: 'es',
          format: 'es',
        },
      ],
    },
  },
  plugins: [svelte()],
});
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 42.83 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.54
    Firefox: 91.0.2
    Safari: 14.0
  npmPackages:
    @sveltejs/vite-plugin-svelte: 1.0.0-next.30 => 1.0.0-next.30 
    svelte: 3.44.0 => 3.44.0 
    vite: 2.6.13 => 2.6.13
```

### Severity

blocking all usage of vite-plugin-svelte

**Comment by shir0u** [comment]
+1 getting the same issue

**Comment by dominikg** [comment]
Hi, this is likely an issue or expected behavior in vite. vite-plugin-svelte doesn't do anything for different rollup output formats.

It's also unclear to me which css option exactly you are referring to as you did not include a reproduction repository or a clear description of what you expect to happen and why you believe this to be a bug in vite-plugin-svelte.

Last but not least this would not qualify as `blocking all usage of vite-plugin-svelte` from what i understand the build output works, it is just not in the form you'd like.

**Comment by shir0u** [comment]
I think it's related to this PR https://github.com/vitejs/vite/pull/5502

**Comment by dominikg** [comment]
Looks like this is an upstream issue in vite. Please file there. @shir0u your PR in vite has a better chance of getting checked out if it includes a reference to an issue and follows their template.
