### ISSUE TITLE
Cleanup prebundleSvelteLibraries

### ISSUE THREAD

**Issue by bluwy** [sveltejs/vite-plugin-svelte#222]
### Describe the problem

Fix the remaining issues for `prebundleSvelteLibraries`, which should be the correct way forward for Vite prebundling of Svelte libraries. Namely:

- [x] Automatic re-prebundle when svelte config change.
- [x] Allow deep importing Svelte components.
- [x] Allow importing libraries with a Svelte component entrypoint.
- [x] Make sure Vite 2.9 prebundling changes works

Some fixes may need to be in Vite core. Collecting these issue here so I don't forget, or if someone likes to tackle them.

### Describe the proposed solution

Goal is to fix them by year end.

### Alternatives considered

Not fix them by year end

### Importance

would make my life easier

**Comment by bluwy** [comment]
Update: no2 and no3 are being dealt at https://github.com/vitejs/vite/pull/6801

**Comment by josdejong** [comment]
Short question: what will be the default behavior after this is finished? Will that be `prebundleSvelteLibraries: true`?

Background: I'm creating a sveltekit library ([see here](https://github.com/josdejong/svelte-jsoneditor/)), but in order to be able to use it right now, every client has to configure `kit.vit.optimizeDeps.include: [...list with commonjs deps...]`. I noticed that this is not needed anymore when setting `experimental.prebundleSvelteLibraries: true`, which is great! So I hope this will become the default in the end: that will make using my library a breeze (just install and use, no extra config needed).

**Comment by bluwy** [comment]
Hi. Ideally this will be the new default behaviour, but I would put it in a short experimental phase first just in case there are edge cases.

> I'm creating a sveltekit library ([see here](https://github.com/josdejong/svelte-jsoneditor/)), but in order to be able to use it right now, every client has to configure `kit.vit.optimizeDeps.include: [...list with commonjs deps...]`

This should be handled by default by `vite-plugin-svelte` already ([nested/transitive dependency inclusion](https://github.com/sveltejs/vite-plugin-svelte/pull/157)), so it's weird that that's needed for your library. I think the `optimizeDeps.include` can be removed now and it will work, but feel free to open an issue if it doesn't.

**Comment by josdejong** [comment]
Awesome!

Good to know that this is supposed to "just" work. I'll double check whether I'm using all the latest versions of svelte/kit/vite and verify whether `optimizeDeps.include` is still needed, if so I'll open a new issue, thanks Bjorn.
