### ISSUE TITLE
How to run svelte-check in dev and see it's errors

### ISSUE THREAD

**Issue by angryziber** [sveltejs/vite-plugin-svelte#308]
### Describe the problem

Vite just strips typescript type information during builds.
While it's fast, it misses all the errors that TS compiler would report and can build wrong code.

### Describe the proposed solution

Is it possible to run svelte-check somehow in parallel to get the errors reported? Preferably in the browser, not only command-line.

### Alternatives considered

Run svelte-check watch as separate process, but this requires constant checking on it.

### Importance

would make my life easier

**Comment by bluwy** [comment]
It's not possible to run svelte-check in parallel because it runs on a whole project basis rather than per-file. So it would be simpler to watch as a separate process.

It's also not possible to display in the browser currently because `svelte-check` is supports CLI mode only currently. Unless it exports some sort of API, it may be possible to create a Vite plugin to display the error in the browser, though I don't think that should be integrated into `vite-plugin-svelte` (?).

For now a separate process is recommended.
