### ISSUE TITLE
direction ltr fix

### ISSUE THREAD

**Issue by mehdiraized** [sveltejs/vite-plugin-svelte#52]
## Description

in RTL projects we have issue

![Screen Shot 2021-06-05 at 22 40 08](https://user-images.githubusercontent.com/4368004/120901291-26c39500-c64f-11eb-837d-88529ccc4d73.png)

**Comment by dominikg** [comment]
Hi,

There seems to be a Syntax error in SidebarCalc.svelte. This is not caused by vite-plugin-svelte, its just the messenger in this case.
Please double check your code, ask for help on svelte discord chat and if this turns out to be a bug, report it again with all of the following:

1) report it in the right repository 
2) use a meaningful title 
3) add a description
4) provide code to reproduce the issue
5) follow the issue template instructions for additional information 

Thanks

**Comment by mehdiraized** [comment]
> Hi,
> 
> There seems to be a Syntax error in SidebarCalc.svelte. This is not caused by vite-plugin-svelte, its just the messenger in this case.
> Please double check your code, ask for help on svelte discord chat and if this turns out to be a bug, report it again with all of the following:
> 
> 1. report it in the right repository
> 2. use a meaningful title
> 3. add a description
> 4. provide code to reproduce the issue
> 5. follow the issue template instructions for additional information
> 
> Thanks

Errors do not matter if direction: ltr in CSS we can read the errors better

**Comment by bluwy** [comment]
The error UI is rendered by Vite itself, not this plugin, so you would have to open an issue there
