### ISSUE TITLE
package.json is missing `main` field

### ISSUE THREAD

**Issue by IanVS** [sveltejs/vite-plugin-svelte#552]
### Describe the bug

Not all tooling supports the package.json `exports` field, including TypeScript when running with `moduleResolution: node` (which is the case for most apps using a bundler).  Is there a reason not to include a `main` field to improve compatibility with existing tooling?

In my particular case, I'm having trouble with eslint's `import/no-extraneous` rule.  It does not think the plugin is installed, but it is. 

### Reproduction URL

https://stackblitz.com/edit/vitejs-vite-yb9bgt?file=src%2Fexample.js&terminal=lint

### Reproduction

Check the example, eslint throws an error.  If you add a `main` to the package.json, the error disappears.

### System Info

```shell
N/A
```

**Comment by dominikg** [comment]
This should be raised at eslint. exports map has a higher priority than main, in fact it means that main must be ignored.

Typescript has it's own `types` condition and we set that, so that should not be a problem if it is, again, raise it with them.

Sorry if this sounds harsh but the whole "main vs module vs browser vs whatever" top level resolve hint field debacle is only going to get worse if people start adding exports maps to the mix instead of replacing the older fields. 

We kept main until we were dropping our commonjs output for backwards compatibility. For all node versions we support, exports maps is supported, so use that.

**Comment by IanVS** [comment]
That's disappointing.  It feels like you're intentionally causing pain to developers like me for purely philosophical reasons.

**Comment by dominikg** [comment]
There is no pain, you can easily change your eslint config to ignore this rule for vite-plugin-svelte, or add a comment to ignore it above the import or contribute a fix to the eslint rule. Rools to resolve exports map exist: https://github.com/lukeed/resolve.exports so having this issue open for 118 months is the cause of this, not us removing main because it is no longer needed.
