### ISSUE TITLE
link to correct source in error page

### ISSUE THREAD

**Issue by weepy** [sveltejs/vite-plugin-svelte#699]
### Describe the bug

Currently the error pages do not link through to the correct page

<img width="698" alt="Screenshot 2023-07-27 at 11 40 22" src="https://github.com/sveltejs/kit/assets/820/bc829a6e-142b-42a6-8944-76f89241cb81">

the link is just relative to the project "/src/lib/components/ProjectMain.svelte:127:17" - but it needs the but it needs the file:// prefix plus the location of the project.

I know it must be possible since with the svelte inspector it's possible to open the relevant component with a click.

### Reproduction URL

https://github.com

### Reproduction

I didn't create a repro since it happens on all repos

### System Info

```shell
Chrome, MacOs, VSCode
```

**Comment by s3812497** [comment]
Not sure if related, but `cmd + click` on the link in the terminal output doesn't open the file either due to the `/` in the beginning?
```bash
6:07:33 PM [vite] Error when evaluating SSR module /src/routes/+page.svelte: failed to import "/src/routes/Counter.svelte"
|- 

Internal server error: /src/routes/Counter.svelte:21:35 Unexpected token
  Plugin: vite-plugin-svelte
  File: /src/routes/Counter.svelte:21:35 # clicking this link
```
With the `/` prefix
![File not found with the / prefix in VS Code](https://github.com/sveltejs/vite-plugin-svelte/assets/54401897/022878d2-3168-4cb1-b7f4-5174f98a37b7)
Without the `/` prefix
![File found without the / prefix in VS Code](https://github.com/sveltejs/vite-plugin-svelte/assets/54401897/1af057e5-32ac-4526-8169-d897325ef255)
