### ISSUE TITLE
Circular filesystem watch events cascade, including self-referential, leading to RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by andriytyurnikov** [sveltejs/vite-plugin-svelte#763]
### Describe the bug

I have encountered crash of dev script.
```
RangeError: Maximum call stack size exceeded
```
Initial investigation lead me to `emitChangeEventOnDependants` function in `src/utils/watch.js`, where I've discovered 
self-referential loops, where supposed `dependant` was same as `filename`.

Unfortunately, blocking self-referential event emitting revealed another problem - circular emission of virtual change event.

It is challenging to create an isolated reproduction. 
Which may or may not be related to how vite-plugin-svelte-cache choses to build dependency tree. 

However, it is clear  that self-referential, and circular references may exist, and therefore may overwhelm nodejs process with storm of emited events.

While it is not as good as reproduction, I hope, you would find this information instrumental.

### Reproduction URL

https://github.com/sveltejs/vite-plugin-svelte

### System Info

```shell
System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M2
    Memory: 208.14 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - ~/.asdf/installs/nodejs/20.8.0/bin/node
    npm: 10.1.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 16.6
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/adapter-static: ^2.0.3 => 2.0.3 
    @sveltejs/kit: ^1.20.4 => 1.25.1 
    svelte: ^4.0.5 => 4.2.1 
    vite: ^4.4.2 => 4.4.10
```

**Comment by bluwy** [comment]
Related: https://github.com/sveltejs/vite-plugin-svelte/issues/690

**Comment by dominikg** [comment]
please provide a reproduction, I'm eager to kearn where this happens. circular dependencies in preprocess dependencies is always an error i think. we can add a guard to avoid the stack error, but would throw a "circular dependency" error instead.

**Comment by andriytyurnikov** [comment]
@dominikg, i get it by commenting and uncommenting styles multiple times in https://github.com/andriytyurnikov/andriytyurnikov.github.io/src/routes/garage/web-font-size-calculator/+page.svelte

BTW, i've commented out "virtual update event" in my local setup. 

Moreover, I have reached a conclusion, which I would like to share: 
emission of such virtual events would be safe only with capability of circular dependency check before emission:
existance of emitChangeEventOnDependants outside of `vite-plugin-svelte-cache` looks like a fundamental mistake.
Without mechanizm to check for circular dependencies, every such virtual event is a potential circular cascade trigger.

Code is written, like there is a guarantee for cascade not to happen, while even simple references existed. I've made an accent on self-references, because it is a simplest case of circular loop, yet it is not prevented. 

Or put it this way: every event emission within event processing may cause the loop. Without explicit guarantees of no loop, such solutions should be discouraged.

Have fun.

**Comment by andriytyurnikov** [comment]
Sorry for jumping all over the place, here is a cleaner formulation:
- event trigering with event processing loop is always a of circular cascade risk
  - which may be mitigated with some isCircular() check
  - or by being performed out of the loop (strongly preferred)

Having (periodic?) event emitter outside of the loop sounds like possible alternative:
instead of `watcher.emit()`, `filesToWatchOutsideOfTheLoop.push()` and `periodicHartbeatEventEmitterOutsideOfTheEventProcessingLoop(filesToWatchOutsideOfTheLoop)`

**Comment by dominikg** [comment]
The fact that we even have to track these dependencies ourselves instead of relying on vite features for it is a bit unfortunate. Not looking into making this more complicated than it already is. In the long time we do this, this is only the second report of a circle happening and i still havn't seen a reproduction for it.


Discussed this with @bluwy  and 2 possible fixes are
1) ensure that the issues we had with vite addWatchFile are gone and switch back, removing all the custom code in v-p-s (preferred)
2) add a guard to prevent the event triggering the overflow

adding a separate periodic mechanism to defer the change event would introduce even more complexity and ways for it to go wrong (things happening out of order etc).

**Comment by andriytyurnikov** [comment]
TLDR; Things are complex and there are 3 paths.
- no "virtual events" (preffered)
- single(!) context for dependency tree checking
- fundamentally redesigned failsafe watcher, capable to withstand circular cascades
Danger! Also, there is a potential workaround hack: accumulate "virtual events" in a buffer, 
and then - periodically, out of the event loop, remove duplicates, and flush that buffer by emitting those events periodically - once in a second or something. Limit the buffer size, for extra safety. Dirty-dirty-dirty. 

Details:
Sad irony is that vite relies on 3rd party watchers (chokidar?), I remember reading their discussion about choosing new one.

I don't mean to be pushy, yet I would like to reiterate for clarity ( and disagreements, questions and critique are totally welcome):
My understanding is that current implementation optimistically assumes:
- impossibility of self-referatial inputs from vite-plugin-svelte-cache
- ability of vite's watcher (!!!) to resolve such cases
As both assumptions are proven(?) to be wrong, I am yet again advise against "virtual event emission", as every such event is a potential trigger for cascade.
 Without cascade-breaker/preventer mechanism in either `watcher`, `vite-plugin-svelte-cache` or `vite-plugin-svelte` such behaviour is fundamentally unsafe.

Also, consider this - circular dependency prevention mechanism based on reference checks is only possible on a level, where full dependency graph is known. With this in mind - having more then one dependency-tracking context is fundamentally vulnerable to cascades as well, as such contexts would be able of triggering each-other.

It is not obvious how exactly watcher (and code triggers event on watcher, which is not the same as communicating dependency tree to vite!) is supposed resolve such an issue: watcher receives "event", and it is not aware that event is "virtual", so watcher tries hard to do his job, regardless of dependency tree - because allowing or disallowing circular references is not it's job - maybe you building a language friendly to circular behaviour.

Apparently, watchers leave issue of dependencies beyond their scope. And, again, it is not surprising, given the need of access to dependency tree for comparison-based implementation. Yet insufficient watcher resiliency is indeed surprising.

**Comment by RowanAldean** [comment]
I just upgraded my entire project to svelte 4 (meaning sveltekit, vite and the rest all updated). Watcher failing and same error as described, I can't save a file without a crash that bubbles up from:
```
at Array.forEach (<anonymous>)
at emitChangeEventOnDependants (node_modules/@sveltejs/vite-plugin-svelte/src/utils/watch.js:22:14)
at node_modules/@sveltejs/vite-plugin-svelte/src/utils/watch.js:94:66
```

Here's a full stack trace:

```
Exception in PromiseRejectCallback:
/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:65205
    });
    ^

RangeError: Maximum call stack size exceeded
/node_modules/@sveltejs/vite-plugin-svelte/src/utils/vite-plugin-svelte-cache.js:167
                const dependants = this.#dependants.get(path);
                                   ^

RangeError: Maximum call stack size exceeded
    at VitePluginSvelteCache.getDependants (/node_modules/@sveltejs/vite-plugin-svelte/src/utils/vite-plugin-svelte-cache.js:167:22)
    at emitChangeEventOnDependants (/node_modules/@sveltejs/vite-plugin-svelte/src/utils/watch.js:21:28)
    at /node_modules/@sveltejs/vite-plugin-svelte/src/utils/watch.js:94:66
    at Array.forEach (<anonymous>)
    at FSWatcher.<anonymous> (/node_modules/@sveltejs/vite-plugin-svelte/src/utils/watch.js:94:44)
    at FSWatcher.emit (node:events:525:35)
    at /node_modules/@sveltejs/vite-plugin-svelte/src/utils/watch.js:27:13
    at Array.forEach (<anonymous>)
    at emitChangeEventOnDependants (/node_modules/@sveltejs/vite-plugin-svelte/src/utils/watch.js:22:14)
    at /node_modules/@sveltejs/vite-plugin-svelte/src/utils/watch.js:94:66

Node.js v18.12.1
```

Much of what you have discussed is far beyond my technical understanding of the sveltekit/svelte ecosystem so i'll pass on trying to understand for now as i'm looking to just build! However I hope the above is of some value (and proof this is happening to others too 👀)

**Comment by andriytyurnikov** [comment]
@RowanAldean , I had same story, in your project's folder you may find file
`node_modules/@sveltejs/vite-plugin-svelte/src/utils/watch.js`
on line `27`
you may see
`watcher.emit('change', dependant);`
comment this line to avoid crashes.

P.S. I have tailwind installed. What would you say about your setup? Are you use anything beyond vanilla setup? Style preprocessors?

**Comment by RowanAldean** [comment]
@andriytyurnikov Thanks, i'll try this and edit comment with result(s).

I'm using `svelte-preprocessor` to support a global `app.scss` via `prependData` in my `svelte.config.js`.

Also using tailwind for [skeletonUI](https://github.com/skeletonlabs/skeleton) and recently for [shadcn-svelte](https://github.com/huntabyte/shadcn-svelte) which is what forced me to do this whole updating everything as I had a bunch of dependency issues.

Also your solution seems painful as this would need to be done anytime I rebuild `node_modules` from `package.json`😢

**Comment by andriytyurnikov** [comment]
@dominikg I wonder if all this jazz is connected with Tailwind recompilation or CSS purging...

... as Tailwind generates CSS classes depending on js files (configs, extensions, plugins), and basically change to any file may cause change of CSS styles, including those inside svelte components 
```
<style></<style>
```
which leads to update of components, which leads to virtual event, which may lead to recompilation of tailwind.... and so on, and so forth...

**Comment by dominikg** [comment]
yes, tailwind with it's postcss directory dependencies could cause this. I'd recommend not using their `@apply` feature in svelte style blocks.

in general I'd recommend unocss instead of it. But given it's popularity and use in 3rd party libraries we have to make it work somehow. still leaning towards keeping it as simple as possible which might mean just avoiding emitting the event in case it's a circle.

**Comment by dominikg** [comment]
yeah, so whats happening here is not pretty at all...
in the project above, these are the dependencies for src/routes/+page.svelte returned by preprocess:
```shell
4:37:24 PM [vite-plugin-svelte] dependencies of andriytyurnikov.github.io/src/routes/+page.svelte
andriytyurnikov.github.io/src/pro-rata.css
andriytyurnikov.github.io/src/index.test.js
andriytyurnikov.github.io/src/lib/index.js
andriytyurnikov.github.io/src/lib/proRata.js
andriytyurnikov.github.io/src/routes/+layout.js
andriytyurnikov.github.io/src/app.html
andriytyurnikov.github.io/src/routes/+layout.svelte
andriytyurnikov.github.io/src/routes/+page.svelte
andriytyurnikov.github.io/src/routes/(app)/+layout.svelte
andriytyurnikov.github.io/src/routes/(app)/garage/+page.svelte
andriytyurnikov.github.io/src/routes/(app)/garage/fundamental/+page.svelte
andriytyurnikov.github.io/src/routes/(app)/garage/fundamental/List.svelte
andriytyurnikov.github.io/src/routes/(app)/garage/fundamental/NavBar.svelte
andriytyurnikov.github.io/src/routes/(app)/garage/fundamental/Shell.svelte
andriytyurnikov.github.io/src/routes/(app)/garage/ideas/+page.svelte
andriytyurnikov.github.io/src/routes/(app)/garage/layouts/+page.svelte
andriytyurnikov.github.io/src/routes/(app)/garage/pro-rata/+page.svelte
andriytyurnikov.github.io/src/routes/(app)/garage/ring-buoy/+page.svelte
andriytyurnikov.github.io/src/routes/(app)/garage/web-font-size-calculator/+page.svelte
andriytyurnikov.github.io/src/routes/(app)/garage/fundamental/list/+page.svelte
andriytyurnikov.github.io/src/routes/(app)/garage/fundamental/navbar/+page.svelte
andriytyurnikov.github.io/src/routes/(app)/garage/fundamental/shell/+page.svelte
andriytyurnikov.github.io/tailwind.config.js
```

including the file we just preprocessed in the dependencies output is obviously super wrong, so step 1 is filtering that from the returned dependencies before passing them on. This means that the direct circle from +page.svelte to +page.svelte no longer happens.

but notice how it includes all the others too? change any of those files and +page.svelte gets preprocessed/compiled again just in case the change actually affected the output.
We have no way to tell which of these dependencies are real and which are just there because tailwind postcss decided to go nuclear.

**Comment by dominikg** [comment]
update: i cannot reproduce this issue with a clean setup of sveltekit and tailwind
```shell
pnpm create svelte@latest kit-tw
// select demo
cd kit-tw
pnpm i
pnpm dlx svelte-add@latest tailwindcss
pnpm dev
```

checking +page.svelte in your app shows you  have `  @import "./../pro-rata.css";` with that file containing 
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

so it's not tailwind going nuclear on it's own, you basically put all of it in your app.svelte style block. This is **not** recommended. instead import that file in the script block of your root layout (where you already import app.css which btw also includes the tailwind directives).

This explains why we don't see more reports of it happening, you really shouldn't do this.

**Comment by dominikg** [comment]
I'm leaning towards throwing an error if we detect the file itself in preprocess dependencies, its a sign of something seriously wrong.

**Comment by andriytyurnikov** [comment]
Well, `app.css` and `<style></style>` a processed independently, so if I want to use utility classes in 
`<style> @apply custom-utility; </style>` - this is the way.

**Comment by andriytyurnikov** [comment]
BTW: with asynchronous load of unnamed component in mind, I can even see the case for "update every `.svelte` component file".

Yet, for SvelteKit case I struggle to see how dependency between `+page.svelte` files can happen.

**Comment by andriytyurnikov** [comment]
I mean if throwing an error is a first step - then sure, otherwise it would just replace `RangeError` with `YourCustomError`.

**Comment by andriytyurnikov** [comment]
"This explains why we don't see more reports of it happening, you really shouldn't do this."
1) I don't think I got the resoning part. Why we should not do it?
2) As you see there were 2 reports in a week. It is unclear how many just give up.

**Comment by andriytyurnikov** [comment]
@RowanAldean It looks like details about your setup and practices might be of use here.

**Comment by dominikg** [comment]
> I don't think I got the resoning part. Why we should not do it?

because `<style>` blocks in .svelte files are scoped to that component, you should not import global css into it. It wasn't tailwind that created this circle on it's own, it was you. tailwind generates styles based on the content of other code files, you told it to look at *.svelte files so they become a dependency of the tailwind styles. And then you go and import the tailwind generated styles into a style block in a .svelte file. 

The Custom error can at least explain it better and link to a FAQ entry clarifying it (eg expand https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#where-should-i-put-my-global-styles to explicitly mention `@import` as another antipattern in scoped style blocks. 

The code tracking these dependencies in vite-plugin-svelte has existed for months (if not years) and it has lots of users. There are popular svelte libraries like skeleton-ui that use svelte with tailwind.  The only other report was on July 18, not last week and also did not provide a reproduction.
If this was a more general issue, there would be more reports.

**Comment by andriytyurnikov** [comment]
Sure, I wanted Tailwind utilities in my scopes, but I get your point, thank you.

**Comment by RowanAldean** [comment]
I wasted more time yak shaving and moved away from scss in favour of pure postcss (hours wasted).

I also removed the explicit dependency on this plugin (it's bundled with sveltekit anyways `"@sveltejs/vite-plugin-svelte" "^2.4.1"`

Since I did this (and admittedly without realising until I saw this thread) I have not had the issue.

However, yes. I was importing my top level stylesheet into my top level `+layout.svelte` and then making that style block `<global>` - this was for the following reasons:

- Use the scss variables declared in my `app.scss`
- Make the other styles in `+layout.svelte` apply to all children routes.

In retrospect I could have removed the block entirely as you mention and put everything in `app.scss` given the reasoning is the same and both are top-level, but I was stupid and now i'm less stupid.

Still i've lost hours refactoring my codebase this weekend and the only real tangible work has been a neat little [shadcn-svelte](https://github.com/huntabyte/shadcn-svelte) slider. Please say a prayer for the giant change and PR being merged soon 🙏
