### ISSUE TITLE
Imported CSS in <style> tag not hot reloading

### ISSUE THREAD

**Issue by rileylyman** [sveltejs/vite-plugin-svelte#838]
### Describe the bug

If you do `@import foo.css` in a component's `<style>` tag, then you change the contents of `foo.css`, the component seems to "fight" against the update in `foo.css` and does not hot reload. The only way to see your change is to delete the `@import` line, save, and then add it back in to get the browser to reflect your changed.

I say that it seems like Svelte is "fighting" against the changes to `foo.css` because if you, say, change the background color of a div in `foo.css` and then reload your browser, you will briefly see the new background color before it goes back to the original color. (EDIT: this only sometimes happens, I can't get it to reproduce reliably.) Again, the only way to make the changes permanent is to delete the `@import` line and then re-add it.

### Reproduction

https://github.com/rileylyman/svelte-import-css-repro

Steps to reproduce:
- `npm run dev`
- observe that the color of the div is orange in your browser
- edit `src/lib/custom.css` to change the background color (to red, say)
- save
- ctrl-R reload your browser and see that the div stays orange (and maybe briefly turns red)
- delete the `@import` line in `src/routes/+page.svelte`
- save
- put the `@import` line back in
- save
- observe that now the div is red (or whatever color you changed it to)

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 19.19 GB / 31.94 GB
  Binaries:
    Node: 21.5.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    npm: 10.2.4 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  Browsers:
    Firefox: 121.0.1
    Chrome: 120.0.6099.217
  npmPackages:
    svelte: ^4.2.7 => 4.2.8
```

### Severity

annoyance

**Comment by dominikg** [comment]
I moved this issue to vite-plugin-svelte as this is what handles hot reloading.

Unfortunately i was not able to reproduce your report. looking at https://stackblitz.com/github/rileylyman/svelte-import-css-repro  everything seems to work just fine (style update immediately being applied and persists with reloading the page too)

It's possible that this issue is only on windows, which i don't have. Please provide additional information by starting the dev server with

`DEBUG=vite-plugin-svelte:* npm run dev -- --debug` and posting the log in three segments

1) after initial load of the dev page
2) after editing the css file without having refreshed/reloaded the dev page
3) after reloading the dev page

**Comment by dominikg** [comment]
Sidenote: 

using `@import` inside style blocks in svelte components isn't ideal. They are scoped styles for that component and importing large stylesheets is likely wasteful. At best it leads to extra processing at buildtime can also lead to larger than needed css output during build, esp. if you import the same css file into different components.

**Comment by dominikg** [comment]
can be reopened if additional information is provided.
