### ISSUE TITLE
Inspector doesn't open respective code part in VSCode when clicked element is not discovered through relative path 

### ISSUE THREAD

**Issue by mcmxcdev** [sveltejs/vite-plugin-svelte#914]
### Describe the bug

We use a Turborepo monorepo with `apps` and `packages` and trying out `@sveltejs/vite-plugin-svelte-inspector` currently.

It's super helpful and opens files with relative paths like `src/lib/components/Foo.svelte` quickly within the app context, but it doesn't seem to work for absolute paths like `$HOME/project/packages/ui/components/Bar.svelte`. It does discover these absolute paths and visualize them in the inspector, but clicking these elements doesn't open anything inside VSCode.

### Reproduction URL

-

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 9.97 GB / 30.71 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.volta/tools/image/node/20.11.0/bin/node
    Yarn: 1.22.22 - ~/.volta/tools/image/yarn/1.22.22/bin/yarn
    npm: 10.2.4 - ~/.volta/tools/image/node/20.11.0/bin/npm
    pnpm: 8.14.1 - ~/.volta/tools/image/pnpm/8.14.1/bin/pnpm
    bun: 1.1.6 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 125.1.66.110
    Chrome: 125.0.6422.76
  npmPackages:
    @sveltejs/adapter-vercel: ^5.3.0 => 5.3.0 
    @sveltejs/kit: ^2.5.7 => 2.5.7 
    @sveltejs/vite-plugin-svelte: ^3.1.0 => 3.1.0 
    svelte: ^4.2.16 => 4.2.16 
    vite: ^5.2.11 => 5.2.11
```

**Comment by dominikg** [comment]
please provide a reproduction, otherwise we are unable to determine if this is an issue within svelte inspector.

Note: The inspector itself does not open files, it only provides the paths given to it from svelte compile to viltes __openInEditor middleware. This middleware uses https://github.com/yyx990803/launch-editor which then calls a shell command for known IDEs in the process list. It probably quotes paths so shell expansion might not work. In general i would not recommend using that and instead use vite aliases to keep references inside the monorepo. Otherwise you end up depending on things outside of your repo (like the presence of $HOME) which is not great.

**Comment by mcmxcdev** [comment]
Ok thanks for the info!

I will provide a repro when I get to it and possibly also look into which codebase is responsible for it, might take me a while though.

**Comment by dominikg** [comment]
i'll close this for now. Once a reproduction has been provided that shows it's the inspectors fault, we'll revisit.
