### ISSUE TITLE
CSP error

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/vite-plugin-svelte#969]
With `vite-plugin-svelte@4.0.0-next.6` sometimes I'm getting an error in console about CSP and I have to restart the svelte-kit server.

No errors at all with `vite-plugin-svelte@3`.

My `svelte.config.js` is:

```js
import adapter from "@sveltejs/adapter-static";
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";
import "dotenv/config";

const dev = process.env.NODE_ENV === "development";

function gen_csp() {
  if (dev) return;

  let directives = {
    "default-src": [`https://*.${process.env.PUBLIC_URL}`],
    "style-src": [
      `https://*.${process.env.PUBLIC_URL}`,
      "unsafe-inline",
    ]
  };

  return { directives };
}

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: vitePreprocess({ script: true }),

  kit: {
    adapter: adapter({
      fallback: "index.html",
    }),

    serviceWorker: {
      register: !dev,
    },

    csp: gen_csp(),
  },
};

export default config;
```

Why?

**Comment by dominikg** [comment]
you've been around long enough to know that we expect reproductions.  its very unlikely that vps causes a csp violation as it only compiles svelte files in isolation and is not involved in serving. Please open a report with a minimal reproduction that includes the actual error message you are getting in the sveltekit repo.

**Comment by frederikhors** [comment]
Here we go, after a few edits in my .svelte files:

```
(index):42 Refused to create a worker from 'http://localhost:4000/service-worker.js' because it violates the following Content Security Policy directive: "script-src https://*.website.com 'nonce-4r1nfez5GdG7nc+4Ce8Wvg=='". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.
(index):42 Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The provided scriptURL ('http://localhost:4000/service-worker.js') violates the Content Security Policy.
localhost/:1 Refused to load manifest from 'http://localhost:4000/manifest.webmanifest' because it violates the following Content Security Policy directive: "default-src https://*.website.com". Note that 'manifest-src' was not explicitly set, so 'default-src' is used as a fallback.
6
Refused to connect to '<URL>' because it violates the following Content Security Policy directive: "connect-src 'self'".
```

**Comment by frederikhors** [comment]
I just switched back to v3. It is unusable because of this.

**Comment by dominikg** [comment]
this is a bug tracker for vite-plugin-svelte, not your personal rant box. please stop

**Comment by lukeed** [comment]
For the record, the error you're getting is **supposed** to happen.

As per [the docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src), if not `worker-src`, then `script-src`, then `default-src`. 

Your `default-src` is `https://*.<public url>`
Your service worker is `http://localhost:4000/service-worker.js`.

Assuming your hostnames are, in fact, matching, your `default-src` is still specifying that it should accept **subdomains** and **https://** only. So, `http://localhost:4000` **should fail** because its 1) not https 2) not a subdomain matching `https://*.website.com`

This is also why your `http://localhost:4000/manifest.webmanifest` file is blocked.

> See [Defining Sources](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources#sources)

You probably want `self` or `http://${public.env.PUBLIC_URL}/` (note the `http` and trailing slash), or perhaps both.

But +1 to what @dominikg said. These messages notify a lot of people, so please be considerate. Even writing this took 10+ minutes, for a single message. It adds up quickly for all OSS maintainers & it's very very tiring in addition to time-consuming. It doesn't even begin to count the amount of time and effort @dominikg pours into developing, maintaining, and/or triaging actual issues for this core/essential plugin for (all of) Svelte ecosystem.

Please seek out channels like the Discord first for these kinds of things
